### ISSUE TITLE
Selenium Elements should flow through Powershell Pipelines

### ISSUE THREAD

**Issue by craigofnz** [adamdriscoll/selenium-powershell#60]
It should be possible to use a Powershell pipeline to chain steps together, such that:

```powershell
$Driver | Enter-SeUrl -url 'https://www.google.com'
$Driver | Find-SeElement -ClassName 'SDkEP' | Find-SeElement -Name 'q' | Send-SeKeys -Keys 'Powershell-Selenium' | Send-SeKeys -Keys ([OpenQA.Selenium.Keys]::Enter)
$Driver | Stop-SeDriver
```

This may lead to a couple of possibly breaking changes if existing scripts do not expect output from certain functions.

Would this feature be desired by the users of this module?

**Comment by jhoneill** [comment]
> Would this feature be desired by the users of this module?

I thought so, so  in #58  instead of doing 
`$driver = start-Browser`
you can now do 
`start-Browser -asDefaultDriver`
Which automatically places the driver in `$Global:SeDriver` ,
`Find-SeElement `and `Enter-SeUrl` (and others) will use `$global:seDriver` if -driver isn't specified

`Stop-SeDriver `and` Find-SeElement` will take a driver from the pipeline. `(Stop-SeDriver` on it's own won't stop the default driver it needs `-Default`) And `Find-SeElement` also takes elements 
Send-SeKeys (and click) will accept an element from the pipeline 

Enter-SeUrl doesn't  take pipeline input of any kind, so allowing a driver to be the piped item would be pretty simple.

**Comment by craigofnz** [comment]
I've been running a private build of this for testing Teams & SPO, with element into and out of pipelines but hadn't PR'd as unexpected outputs could have produced a breaking change. As we are targeting a v3, I'll bring them in after resolving merges. I suspect it will work well with the DSL approach that jhoneill is working toward.

**Comment by craigofnz** [comment]
Integrated in PR #62 / [commit f9eba1d](https://github.com/adamdriscoll/selenium-powershell/commit/f9eba1da1d76604d11c94ec0a9267d28249dcd8d)
