### ISSUE TITLE
Unsigned 2.0

### ISSUE THREAD

**Issue by PhelixPhoenix** [adamdriscoll/selenium-powershell#75]
Due to the corporate environment I cannot change my execution policy to allow this to run.

Import-Module : File C:\Users\uname\Desktop\script\selenium-powershell-2.0\Selenium.psm1 cannot be loaded. The file 
C:\Users\uname\Desktop\script\selenium-powershell-2.0\Selenium.psm1 is not digitally signed. You cannot run this script on the current system. For more information about running 
scripts and setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At C:\Users\uname\Desktop\ script\ script.ps1:28 char:1
+ Import-Module "C:\Users\uname\Desktop\script\selenium-pow ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [Import-Module], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess,Microsoft.PowerShell.Commands.ImportModuleCommand
Start-SeInternetExplorer : The term 'Start-SeInternetExplorer' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again.

**Comment by Schwanowski** [comment]
You need to set the executionpolicy or to install it via install-module.

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-7

**Comment by Spiker985** [comment]
You can also start PowerShell from a batch file with the `-ExecutionPolicy Bypass` parameter to allow that PowerShell instance to use the proposed policy instead of the system default.
`start "Title" "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoExit -ExecutionPolicy Bypass`

- `start` is the batch command to start a process.
- `"Title"` is mandatory, but can be an empty ""
- Full path to the executable 
- `-NoExit` prevents PowerShell from exiting after opening
- `-ExecutionPolicy Bypass` forces the Bypass Policy

You can read more about PowerShell's command line options by using `Get-Help about_PowerShell.exe`

You can also use PowerShell to launch another PowerShell instance with mostly the same process, following `Get-Help Start-Process`

**Comment by itfranck** [comment]
This issue is answered and inactive for some time. I am archiving it. Feel free to reopen if this is not resolved.
