### ISSUE TITLE
Please add support for UserAgent in web drivers

### ISSUE THREAD

**Issue by MVKozlov** [adamdriscoll/selenium-powershell#91]
Please add support for UserAgent in web drivers

at least for Chrome it just

```$Options.AddArguments("user-agent=$UserAgent")```

btw, may be there is a reason for `New-SeChromeDriverOptions` and
`Start-SeChrome -Options $Options` way ?

**Comment by itfranck** [comment]
@MVKozlov 

The arguments parameter can allow you to pass additional options. 
(It does the `$Options.AddArguments` behind the scene )

For instance
```
$Driver = Start-SeChrome -StartURL 'https://www.google.ca' -AsDefaultDriver -Arguments ("user-agent=Android")
```

I'll keep this ticket open though as I'd see this implemented as a parameter with an argument completer so it is more transparent.

**Comment by itfranck** [comment]
Because there's no unilateral support for all the browsers (eg: IE do not support user agent changes, Firefox require setting up a profile, etc..), I can't add an explicit **useragent** parameter that would accomodate all browser but as mentionned previously, I added argument completion for V4 to suggest some of the most useful parameters so it make it setting it for Chrome a little bit easier.

![image](https://user-images.githubusercontent.com/1980296/93715066-e1991a80-fb34-11ea-851b-8b7dc841d28f.png)

**Comment by itfranck** [comment]
@MVKozlov Done. It will be available for V4 as a parameter.
Note that only Firefox and Chrome support this.
