### ISSUE TITLE
Start-SeChrome object is not being recognized

### ISSUE THREAD

**Issue by JohnGhannam** [adamdriscoll/selenium-powershell#95]
It looks like this is a bug

![image](https://user-images.githubusercontent.com/12851447/84288104-bef76e80-ab0e-11ea-9876-5eb0522f3882.png)

**Comment by ecspresso** [comment]
The problem is that the driver shipped with module is older than the version of Chrome you have installed.

Assuming you are running Chrome version 83 on your computer, download the latest version here: https://chromedriver.storage.googleapis.com/index.html?path=83.0.4103.39/

Then extract `chromedriver.exe` and replace `\Selenium\3.0.0\assemblies\chromedriver.exe` with the extacted file.

If you do not know where the module is installed, you can run this code:
```
Import-Module -Name Selenium
Get-Module -Name Selenium | Select-Object -ExpandProperty 'Path'
```

**Comment by JohnGhannam** [comment]
That worked  

Thank you
